### ISSUE TITLE
Fails to load, import error (groundingdino)

### ISSUE THREAD

**Issue by aurel-g** [mrhan1993/ComfyUI-Fooocus#2]
```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/__init__.py", line 7, in <module>
    from .nodes import *
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/nodes.py", line 13, in <module>
    from node_utils import params_to_params, AlwaysEqualProxy
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/node_utils.py", line 4, in <module>
    from apis.models.requests import (
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/apis/models/requests.py", line 8, in <module>
    from apis.models.base import (
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/apis/models/base.py", line 9, in <module>
    from modules.async_worker import AsyncTask
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/modules/async_worker.py", line 6, in <module>
    from extras.inpaint_mask import SAMOptions, generate_mask_from_image
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/extras/inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus/extras/GroundingDINO/util/inference.py", line 12, in <module>
    from groundingdino.util.inference import Model
ModuleNotFoundError: No module named 'groundingdino'

Cannot import /mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus module for custom nodes: No module named 'groundingdino'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.5 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/ComfyUI-Fooocus

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by mrhan1993** [comment]
install `groundingdino-py` package and try again

`pip install groundingdino-py==0.4.0`

**Comment by aurel-g** [comment]
Yes it worked, thank you
